---

- name: deploy_vm.yml | All roles
  hosts: localhost
  gather_facts: yes
  #remote_user: root
  remote_user: ansible
  become: yes
  vars_files:
    - ../group_vars/deploy_vm/deploy_vm.yml
    - ../group_vars/deploy_vm/deploy_vm-password.yml


  roles:
    - { role: ansible_role_proxmox_deploy_vm,                   tags: ["proxmxo_deploy_vm"] }
