---

- name: gitlab.yml | All roles
  hosts: hf-t-test01
  gather_facts: yes
  #remote_user: root
  remote_user: ansible
  become: yes

  roles:
    - { role: ansible-role-gitlab,                   tags: ["gitlab"] }
