---

- name: template-play.yml | All roles
  hosts: gitlab
  gather_facts: yes
  #remote_user: root
  remote_user: ansible
  become: yes
  vars_files:
    - ../group_vars/template-play.yml
    - ../group_vars/template-play-secrets.yml


  roles:
    - { role: ansible-role-gitlab,                   tags: ["gitlab"] }
